version: 2
updates:
    -   package-ecosystem: "github-actions"
        directory: "/"
        schedule:
    -   package-ecosystem: "maven"
        directory: "/"
        schedule:
    -   package-ecosystem: "docker"
        directory: "/"
        schedule:
